"""empty message

Revision ID: 062d17773e89
Revises: 51626ca38193
Create Date: 2022-01-10 15:52:37.143345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062d17773e89'
down_revision = '51626ca38193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_error_logs_created', table_name='error_logs')
    op.drop_index('ix_xrate_from_currency', table_name='xrate')
    op.drop_index('ix_xrate_to_currency', table_name='xrate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_xrate_to_currency', 'xrate', ['to_currency'], unique=False)
    op.create_index('ix_xrate_from_currency', 'xrate', ['from_currency'], unique=False)
    op.create_index('ix_error_logs_created', 'error_logs', ['created'], unique=False)
    # ### end Alembic commands ###
