"""empty message

Revision ID: 2efd573c1e13
Revises: f0a77048714b
Create Date: 2022-01-10 13:18:51.374398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efd573c1e13'
down_revision = 'f0a77048714b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_url', sa.String(), nullable=True),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(), nullable=True),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_logs_created'), 'api_logs', ['created'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_url', sa.String(), nullable=True),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_created'), 'error_logs', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_logs_created'), table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_api_logs_created'), table_name='api_logs')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
