"""empty message

Revision ID: 51626ca38193
Revises: c3dfc7ec17c1
Create Date: 2022-01-10 15:50:37.226263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51626ca38193'
down_revision = 'c3dfc7ec17c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_xrate_from_currency'), 'xrate', ['from_currency'], unique=False)
    op.create_index(op.f('ix_xrate_to_currency'), 'xrate', ['to_currency'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xrate_to_currency'), table_name='xrate')
    op.drop_index(op.f('ix_xrate_from_currency'), table_name='xrate')
    # ### end Alembic commands ###
