"""empty message

Revision ID: 5859d5f14c4e
Revises: e95e78b94cc5
Create Date: 2022-01-10 14:09:04.590485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5859d5f14c4e'
down_revision = 'e95e78b94cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.Integer(), nullable=True),
    sa.Column('to_currency', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xrate_from_currency'), 'xrate', ['from_currency'], unique=False)
    op.create_index(op.f('ix_xrate_to_currency'), 'xrate', ['to_currency'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xrate_to_currency'), table_name='xrate')
    op.drop_index(op.f('ix_xrate_from_currency'), table_name='xrate')
    op.drop_table('xrate')
    # ### end Alembic commands ###
