"""empty message

Revision ID: c3dfc7ec17c1
Revises: 7fde865ce0be
Create Date: 2022-01-10 14:58:15.634328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3dfc7ec17c1'
down_revision = '7fde865ce0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_url', sa.String(), nullable=True),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(), nullable=True),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_logs')
    # ### end Alembic commands ###
