"""empty message

Revision ID: fefebc987636
Revises: 2efd573c1e13
Create Date: 2022-01-10 13:20:05.280502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefebc987636'
down_revision = '2efd573c1e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_xrate_from_currency'), 'xrate', ['from_currency'], unique=False)
    op.create_index(op.f('ix_xrate_to_currency'), 'xrate', ['to_currency'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xrate_to_currency'), table_name='xrate')
    op.drop_index(op.f('ix_xrate_from_currency'), table_name='xrate')
    # ### end Alembic commands ###
